version: '2'
services:
  mariadb:
    image: 'registry.cn-hangzhou.aliyuncs.com/opencart3_0_3_2/opencart3:opencart_mariadb_10.3'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: web-database
    volumes:
      - 'mariadb_data:/bitnami'
  
  
  web:
    image: 'registry.cn-hangzhou.aliyuncs.com/opencart3_0_3_2/opencart3:opencart'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=opencart66.com
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: web-app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'opencart_data:/bitnami'
      - "./resource/datafile:/bitnami/opencart/image/catalog/datafile"
      - "./resource/zhadmin/zh-cn:/opt/bitnami/opencart/admin/language/zh-cn"
      - "./resource/zhcus/zh-cn:/opt/bitnami/opencart/catalog/language/zh-cn"
      - "./resource/datafile/logo.png:/opt/bitnami/opencart/admin/view/image/logo.png"   
    depends_on:
      - mariadb

  config:  
    build:
      context: .
      dockerfile:  Dockerfile_config
    container_name: config-app
    depends_on:
      - web  


  # poc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_poc
  #   container_name: poc-app
  #   depends_on:
  #     - opencart
  #     - config

  


volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
